require('include')
function testVector()
    local a, b = cg.Vector(0, 10), cg.Vector(5, 5)
    a:projection(b):assertAlmostEquals(cg.Vector(0, 5))
    a:rejection(b):assertAlmostEquals(cg.Vector(5, 0))
    a, b = cg.Vector(0, 5), cg.Vector(10, 10)
    a:projection(b):assertAlmostEquals(cg.Vector(0, 10))
    a:rejection(b):assertAlmostEquals(cg.Vector(10, 0))
    a, b = cg.Vector(0, 10), cg.Vector(-5, 5)
    a:projection(b):assertAlmostEquals(cg.Vector(0, 5))
    a:rejection(b):assertAlmostEquals(cg.Vector(-5, 0))
end
os.exit(lu.LuaUnit.run())