name: Question [EN]
description: You got a question? Just ask!
labels:
- question
assignees:
- Tensuko
body:
- type: markdown
  attributes:
    value: 'Please use this template to ask your question!

      Please make sure to read our [Wiki Page](https://github.com/Courseplay/Courseplay_FS22/wiki)
      before creating a new issue!

      Our help pages from the game can also be found at [Courseplay.dev]!(https://courseplay.github.io/Courseplay_FS22.github.io/),
      there you can check out many informations before asking a qustion!

      '
- type: dropdown
  id: mod-version
  attributes:
    label: Version
    description: Which CoursePlay version are you using?
    options:
    - 7.1.0.0
    - 7.1.0.3
    - 7.2.0.0
    - 7.2.0.5
    - 7.3.0.0
    - 7.3.0.1
    - 7.3.0.2
    - 7.3.0.3
    - 7.3.1.0
    - 7.3.1.1
    - 7.3.1.2
    - 7.3.1.3
    - 7.3.1.4
    - 7.3.1.5
    - 7.4.0.0
    - 7.4.0.1
    - 7.4.0.2
    - 7.4.1.0
    - 7.4.1.1
    - 7.4.1.2
    - 7.4.1.3
    - 7.4.2.0
    - 7.4.2.1
    - 7.4.2.2
    - 7.4.2.3
    - 7.4.2.4
    - 7.5.0.0
    default: 26
  validations:
    required: true
- type: dropdown
  id: spmp
  attributes:
    label: SP/MP
    description: Did the bug happen in SP or MP?
    options:
    - SP (Singleplayer)
    - MP (Multiplayer)
    default: 0
  validations:
    required: true
- type: dropdown
  id: about
  attributes:
    label: What is your question about?
    description: Select a category.
    options:
    - Course creation
    - Vehicle settings
    - Global CP settings
    - more later
    default: 0
  validations:
    required: true
- type: textarea
  id: question
  attributes:
    label: What is your question?
    description: Question
    placeholder: Question
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: Use drag and drop into the textbox to upload the screenshots.
    placeholder: If you have any helpful screenshots to describe the situation, please
      add them here.
  validations:
    required: true
