name: Reusable workflow example

on:
  workflow_call:
    inputs:
      sha_begin:
        required: true
        type: string
      sha_end:
        required: true
        type: string
      author:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  get-changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    steps:
      - name: Get gif-diff
        id: getfiles
        run: |
          echo "::set-output name=files::$(git diff-tree --name-only -r ${{ github.sha }} | xargs)"
      - name: Output git-diff
        run: |
          echo ${{ steps.getfiles.outputs.files }}