# The workflow name
name: Run unit tests

# Controls when the workflow will run
# - pull_request will trigger when a PR is made and when new commits are made on a PR
# - workflow_dispatch is a manual trigger
on: 
  pull_request:
  workflow_dispatch:

# The list of jobs this workflow executes
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Lua
        uses: xpol/setup-lua@v0.3
      - name: Run unit tests
        run:  cd scripts\test && lua CourseManagerTest.lua
