
# 1) This workflow formats and updates the translation files.
# 2) Adds translators to the contributor files.

# Original implementation by: https://github.com/Thodor12

# The workflow name
name: Update translations and contributors

# Controls when the workflow will run
on: 
  push:
    paths:
      - "**/translations/**"
      - "**/config/MasterTranslations.xml"
  pull_request:
    branches:
      - main
    paths:
      - "**/translations/**"
      - "**/config/MasterTranslations.xml"

# The list of jobs this workflow executes
jobs:
  # Updates the translations
  update_translations:
    name: Update translations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Update translation xml files.
        run: | 
          python -m pip install lxml
          python .github/scripts/update-translations/updateTranslations.py
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated translations

  get_all_files:
    name: Get all files
    runs-on: ubuntu-latest
    needs: [update_translations]
    outputs:
      files: ${{ steps.changedFiles.outputs.all_changed_files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Get changed files
        id: changedFiles
        uses: tj-actions/changed-files@v23
      - name: List all changed files
        run: |
          for file in ${{ steps.changedFiles.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
  update_contributors:
    name: Update contributors
    runs-on: ubuntu-latest
    needs: [get_all_files, update_translations]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      # Pulls the translation changes from above.
      - name: Pull changes
        run:
          git pull origin
      - name: Create local changes
        run: |
          cd .github/scripts/update-contributors
          node index.js ${{ github.actor }} ${{ needs.get_all_files.outputs.files }}
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated contributors